[General]
ApplicationVersion = '''0.4.3'''
FreeSpaceSearch = '''000200'''
FreeSpaceBuffer = '''100'''
NextExportID = '''0'''

#################################
#################################
#################################
#################################
#################################
#################################
