	const_def 1
	const GRASS_ENERGY                ; $01
	const FIRE_ENERGY                 ; $02
	const WATER_ENERGY                ; $03
	const LIGHTNING_ENERGY            ; $04
	const FIGHTING_ENERGY             ; $05
	const PSYCHIC_ENERGY              ; $06
	const DOUBLE_COLORLESS_ENERGY     ; $07
	const BULBASAUR                   ; $08
	const IVYSAUR                     ; $09
	const VENUSAUR_LV67               ; $0a
	const VENUSAUR_LV64               ; $0b
	const CATERPIE                    ; $0c
	const METAPOD                     ; $0d
	const BUTTERFREE                  ; $0e
	const WEEDLE                      ; $0f
	const KAKUNA                      ; $10
	const BEEDRILL                    ; $11
	const EKANS                       ; $12
	const ARBOK                       ; $13
	const NIDORANF                    ; $14
	const NIDORINA                    ; $15
	const NIDORANM                    ; $17
	const NIDORINO                    ; $18
	const NIDOQUEEN                   ; $16
	const NIDOKING                    ; $19
	const ZUBAT                       ; $1a
	const GOLBAT                      ; $1b
	const PINSIR                      ; $2f
	const ODDISH                      ; $1c
	const GLOOM                       ; $1d
	const VILEPLUME                   ; $1e
	const PARAS                       ; $1f
	const PARASECT                    ; $20
	const VENONAT                     ; $21
	const VENOMOTH                    ; $22
	const BELLSPROUT                  ; $23
	const WEEPINBELL                  ; $24
	const VICTREEBEL                  ; $25
	const GRIMER                      ; $26
	const MUK                         ; $27
	const EXEGGCUTE                   ; $28
	const EXEGGUTOR                   ; $29
	const KOFFING                     ; $2a
	const WEEZING                     ; $2b
	const TANGELA_LV8                 ; $2c
	const TANGELA_LV12                ; $2d
	const SCYTHER                     ; $2e
	const CHARMANDER                  ; $30
	const CHARMELEON                  ; $31
	const CHARIZARD                   ; $32
	const VULPIX                      ; $33
	const NINETALES_LV32              ; $34
	const NINETALES_LV35              ; $35
	const GROWLITHE                   ; $36
	const ARCANINE_LV45               ; $37
	const PONYTA                      ; $38
	const RAPIDASH                    ; $39
	const MAGMAR_LV24                 ; $3a
	const MAGMAR_LV31                 ; $3b
	const FLAREON_LV22                ; $3c
	const ARCANINE_LV34               ; $3d
	const FLAREON_LV28                ; $3e
	const MOLTRES_LV35                ; $3f
	const MOLTRES_LV37                ; $40
	const SQUIRTLE                    ; $41
	const WARTORTLE                   ; $42
	const BLASTOISE                   ; $43
	const PSYDUCK                     ; $44
	const GOLDUCK                     ; $45
	const POLIWAG                     ; $46
	const POLIWHIRL                   ; $47
	const POLIWRATH                   ; $48
	const TENTACOOL                   ; $49
	const TENTACRUEL                  ; $4a
	const SEEL                        ; $4b
	const DEWGONG                     ; $4c
	const SHELLDER                    ; $4d
	const CLOYSTER                    ; $4e
	const KRABBY                      ; $4f
	const KINGLER                     ; $50
	const HORSEA                      ; $51
	const SEADRA                      ; $52
	const GOLDEEN                     ; $53
	const SEAKING                     ; $54
	const STARYU                      ; $55
	const STARMIE                     ; $56
	const MAGIKARP                    ; $57
	const GYARADOS                    ; $58
	const LAPRAS                      ; $59
	const VAPOREON_LV29               ; $5a
	const VAPOREON_LV42               ; $5b
	const OMANYTE                     ; $5c
	const OMASTAR                     ; $5d
	const ARTICUNO_LV35               ; $5e
	const ARTICUNO_LV37               ; $5f
	const PIKACHU_LV12                ; $60
	const RAICHU_LV40                 ; $61
	const PIKACHU_LV16                ; $62
	const RAICHU_LV45                 ; $63
	const PIKACHU_ALT_LV16            ; $64
	const FLYING_PIKACHU              ; $65
	const SURFING_PIKACHU_LV13        ; $66
	const SURFING_PIKACHU_ALT_LV13    ; $67
	const PIKACHU_LV14                ; $68
	const MAGNEMITE_LV13              ; $69
	const MAGNETON_LV28               ; $6a
	const MAGNETON_LV35               ; $6b
	const VOLTORB                     ; $6c
	const ELECTRODE_LV35              ; $6d
	const ELECTRODE_LV42              ; $6e
	const ELECTABUZZ_LV35             ; $6f
	const ELECTABUZZ_LV20             ; $70
	const JOLTEON_LV24                ; $71
	const JOLTEON_LV29                ; $72
	const MAGNEMITE_LV15              ; $73
	const ZAPDOS_LV40                 ; $74
	const ZAPDOS_LV64                 ; $75
	const ZAPDOS_LV68                 ; $76
	const SANDSHREW                   ; $77
	const SANDSLASH                   ; $78
	const DIGLETT                     ; $79
	const DUGTRIO                     ; $7a
	const MANKEY                      ; $7b
	const PRIMEAPE                    ; $7c
	const MACHOP                      ; $7d
	const MACHOKE                     ; $7e
	const MACHAMP                     ; $7f
	const GEODUDE                     ; $80
	const GRAVELER                    ; $81
	const GOLEM                       ; $82
	const ONIX                        ; $83
	const CUBONE                      ; $84
	const MAROWAK_LV32                ; $85
	const MAROWAK_LV26                ; $86
	const HITMONLEE                   ; $87
	const HITMONCHAN                  ; $88
	const RHYHORN                     ; $89
	const RHYDON                      ; $8a
	const KABUTO                      ; $8b
	const KABUTOPS                    ; $8c
	const TYRUNT					  ; $ea
	const AERODACTYL                  ; $8d
	const ABRA                        ; $8e
	const KADABRA                     ; $8f
	const ALAKAZAM                    ; $90
	const SLOWPOKE_LV9                ; $91
	const SLOWPOKE_LV18               ; $92
	const SLOWBRO                     ; $93
	const GASTLY_LV8                  ; $94
	const HAUNTER_LV17                ; $96
	const GENGAR                      ; $98
	const GASTLY_LV17                 ; $95
	const HAUNTER_LV22                ; $97
	const DROWZEE                     ; $99
	const HYPNO                       ; $9a
	const MR_MIME                     ; $9b
	const JYNX                        ; $9c
	const MEWTWO_LV53                 ; $9d
	const MEWTWO_LV60                 ; $9e
	const MEWTWO_ALT_LV60             ; $9f
	const MEW_LV8                     ; $a0
	const MEW_LV15                    ; $a1
	const MEW_LV23                    ; $a2
	const PIDGEY                      ; $a3
	const PIDGEOTTO                   ; $a4
	const PIDGEOT_LV38                ; $a5
	const RATTATA                     ; $a6
	const RATICATE                    ; $a7
	const SPEAROW                     ; $a8
	const FEAROW                      ; $a9
	const CLEFAIRY                    ; $aa
	const CLEFABLE                    ; $ab
	const JIGGLYPUFF_LV12             ; $ac
	const JIGGLYPUFF_LV14             ; $ad
	const WIGGLYTUFF                  ; $ae
	const MEOWTH_LV15                 ; $af
	const PERSIAN                     ; $b0
	const JIGGLYPUFF_LV13             ; $b1
	const MEOWTH_LV14                 ; $b2
	const PIDGEOT_LV40                ; $b3
	const FARFETCHD                   ; $b4
	const DODUO                       ; $b5
	const DODRIO                      ; $b6
	const LICKITUNG                   ; $b7
	const CHANSEY                     ; $b8
	const KANGASKHAN                  ; $b9
	const TAUROS                      ; $ba
	const DITTO                       ; $bb
	const EEVEE                       ; $bc
	const PORYGON                     ; $bd
	const SNORLAX                     ; $be
	const DRATINI                     ; $bf
	const DRAGONAIR                   ; $c0
	const DRAGONITE_LV45              ; $c2
	const DRAGONITE_LV41              ; $c1
	const PROFESSOR_OAK               ; $c3
	const IMPOSTER_PROFESSOR_OAK      ; $c4
	const BILL                        ; $c5
	const MR_FUJI                     ; $c6
	const LASS                        ; $c7
	const IMAKUNI_CARD                ; $c8
	const POKEMON_TRADER              ; $c9
	const POKEMON_BREEDER             ; $ca
	const CLEFAIRY_DOLL               ; $cb
	const MYSTERIOUS_FOSSIL           ; $cc
	const ENERGY_RETRIEVAL            ; $cd
	const SUPER_ENERGY_RETRIEVAL      ; $ce
	const ENERGY_SEARCH               ; $cf
	const ENERGY_REMOVAL              ; $d0
	const SUPER_ENERGY_REMOVAL        ; $d1
	const SWITCH                      ; $d2
	const POKEMON_CENTER              ; $d3
	const POKE_BALL                   ; $d4
	const SCOOP_UP                    ; $d5
	const COMPUTER_SEARCH             ; $d6
	const POKEDEX                     ; $d7
	const PLUSPOWER                   ; $d8
	const DEFENDER                    ; $d9
	const ITEM_FINDER                 ; $da
	const GUST_OF_WIND                ; $db
	const DEVOLUTION_SPRAY            ; $dc
	const POTION                      ; $dd
	const SUPER_POTION                ; $de
	const FULL_HEAL                   ; $df
	const REVIVE                      ; $e0
	const MAINTENANCE                 ; $e1
	const POKEMON_FLUTE               ; $e2
	const GAMBLER                     ; $e3
	const RECYCLE                     ; $e4
	const DUCKLETT                    ; $e5
	const TYNAMO                      ; $e6
	const EELEKTROSS				  ; $e7
	const EELEKTRIK				      ; $e8
	const DRAPION                     ; $e9
	const FUECOCO					  ; $eb
	const CROCALOR					  ; $ec
	const SKELEDIRGE				  ; $ed
	const BELDUM 					  ; $ee
	const METANG					  ; $ef
	const METAGROSS					  ; $f1
	const BAGON 					  ; $f2
	const SHELGON 					  ; $f3
	const SALAMENCE 					  ; $f4
	const ROCKRUFF					; $f7
	const LYCANROC				; $f8
	const LYCANROCM				; $f9
	const REGIELEKI			; $111
	const DRUDDIGON 				   ; $112
	const MAGBY						   ; $113
	const MAG2						   ; $114
	const MAGMORTAR					   ; $115
	const HOOH						   ; $116
	const MUNNA							; $117
	const MUSHARNA						; $118
DEF NUM_CARDS EQU const_value - 1
